export default function Disclaimer() {
  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <h1 className="text-2xl font-bold text-white">Disclaimer</h1>
      <div className="card text-slate-300 text-sm leading-relaxed space-y-4">
        <p>
          The information contained in this website is provided for general public, researchers, educators and
          students which is generated by the MGD team and gathered from different resources. While we endeavor to
          keep the information up to date and correct, we make no representations or warranties of any kind,
          express or implied, about the completeness, accuracy, reliability, suitability or availability with
          respect to the website or the information or related graphics contained on the website for any purpose.
          Any reliance you place on such information is therefore strictly at your own risk.
        </p>
        <p>
          In no event will we be liable for any loss or damage including without limitation, indirect or
          consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits
          arising out of, or in connection with, the use of this website.
        </p>
        <p>
          Through this website you are able to link to other websites which are not under the control of Mango
          Genome Database. We have no control over the nature, content and availability of those sites. The
          inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within
          them.
        </p>
        <p>
          Every effort is made to keep the website up and running smoothly. However, MGD team takes no
          responsibility for, and will not be liable for, the website being temporarily unavailable due to
          technical issues beyond our control.
        </p>
      </div>
    </div>
  );
}
